# Generated by Django 3.0 on 2020-04-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
