# Generated by Django 3.0 on 2020-04-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
